travis:
  secure:
    BINSTAR_TOKEN: TH7xdM5AV5+Q1uhBuHJpSe/FWfLUg9HkJXN5JYfYnzQsZO1gvP3TcXglXtEHxurfnEwu1GLxZX4lnR8ORKZt9TgBk/vx6uCLCezo/T55dT8+VIR+2vVN7sZIE6Virzf5gd7O79kbFGA7W4+nxx+IAioFwsl9819Vt5QA7xS2peQMbU+b2JVtf8vc28NFCjJcnZ5X/RP+6pi04Y/SBzH/dR3avFYquD80QGOiGDUF582d4r8iR5mnLbAF2YFEI6Yh9Sa8fUlvupxtOdI6DM+Re1kLl+yHctraptpIw6oqrIJlUADW+NvxfE7wccIPPvXjBnkEwjet7ChXqdFVg/MM7vwKjvVcBg3W1aeUv/vQlhg76K6XJCkQdkRK7Ym+L0SbTgDbeU9W/pXOl8Qw+5rP8Ineh+2+SIAljiWR3k8/wOmbTzjItNHn9S87elWry/4RJbU2wYWsNEZtM75HhE4rYRy4z04vQPdcyW2V8ZLa9huF6NnU8cqoj6Yh/tUYANWatMEUX3SvGNbARoOHPZ9iHnS5oDUTQOvYU90o3+2QJf/EX77pRwHHJgwIRdJq+UyB46WWs7fEC0PMpU6jPJS51hmKDuIa6rFPRX3LMVc+gv4PqDoMz1sGBZN1Ofze0B/DtlDB4Iv+H045k+3r9O2cUZzfN0dIqLG9vsGV6d67jeI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
