travis:
  secure:
    BINSTAR_TOKEN: ijgEc/SFy18k5jWQ5l8jw7hhqQbdlCpLc5x2p2EUEHVuSfUQaplCODXhpJumrwzsWtcPn6TGdBW3g2V+q1baOYia26tlBISEmP+f9s4H6EHDeUbF/piwYjXB9UJV/CW+2f4BV4Z1Gms0XX4WscI0vsjie9eMCiem75JILhuuhsyMfsNhfYFv9tqAsw0aI0QYHNrp/S4dfLNi3bsfimxnzK4jO6Xv9I4RpFd9oorfIPugbKkbPUODr8ProJxXrRWy9mUNTnfjWBFws0rfTpKVmW6V/4/FJSR/W02aAnHQENC2fn4X/Rm6gIuhCATQoBPxjYkiWOJ0zQkRdX8YY2aCSeIEc9Eflq6ZdASjQRlzIWnU6P9AqVetEf4lndNYfSVPwwp7OMAILX91w3oDqdOHcaNmZFmZ7JliePQJGc9K2v+Jx18k/52Axq2QWsduFVsomEKyk/1fgO7TpGJQXHS+Fgz7wnzNes+EIRQms8snwNa/PAXOyZHzFYnyeB6Z4UyU0pXXb00omKG8wqznLhCFAcOFPD9OqTd9YnwycPo8iXgTi+2FjRm4PbF+o9FXb2SUV0atsj+XJPdHtvG2L/BTPYQV98OpmDRMrQJ+87O59IXgXr0ueKxWZkX4fCZTbl9lNgQ3JW8KT7pOzUy90dp+caz1u9P+rKcuWtlIhUCP7/A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
