travis:
  secure:
    BINSTAR_TOKEN: BR7Id48DVzwnRh54d/+Or9mF4vCsdWAWJua3XOxvdyTnXXumgqkqqBq9Yq3vli4pNqZu6fJf3WMF5z88tzPIfZn+/SEH+zh/Ck0L4PCGqa8e516HaEE0KanrtrxjX2X/Yo3/IMGPeci8cT9PQboPFM4xoPsPmTBT09mCGJBPO9uEbLFEVtQuLo8XgnHQv96Ooeh1aS9GrcW8EOGO2ORufrqK/BfdQwETvhfOBgR9LcpLZGr3RlhMSl7qN7ORrB1cZ30VGjbpKxEMJrDce14Ok65dZt4fE2GXKnWup0v1UNSJhoggH0LYog7dGhzDZXHfHvlvnyt9x0gdEhanngFD/VijSksf9MeZ5c+p5dh1JHAGJbpUsZ42Nkkg7RvTDiRKr8AZb2/zqdhnLk2gQHN9LbHPcEw9Jfp8CmqFkV/s846ZXRjvAP1zdDowUeVaMrMP60z2RT+HppBRf9teIv7qqtYMOPvmo0yiG+07Wg0t0ztDLHbGrlzE2aCSVlEQjWrsDL3S4krLM/2StsjN1z+DdgXlWVRmzT2WfJNQMIkCCT9tdnfPz51+ZS+qVSlM6R44Fkb1D4MWRbxZqFti/0JGC8xG381GKpUkpTq/ILSiu/32UH1xnYJMXOovEya54MiHtO9lmI/xpdYcTStaC3i2h+4wcHzBy2I+9b8TvJPttF4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
